spring:
  application:
    name: meshmind
  config:
    import: optional:file:.env[.properties]
langchain4j:
  google:
    ai:
      gemini:
        api-key: ${GEMINI_API_KEY}
        model-name: gemini-2.5-flash